version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
  build:
    commands:
      - echo Build started
  post_build:
    commands:
      - echo Build completed

#artifacts:
 # files:
  #  - '**/*'
phases:
  build:
    commands:
      - echo "Deploying to S3"
      - aws s3 sync . s3://new-lalitha-buc --delete
      - aws cloudfront create-invalidation --E2ZOD15NSRBNYJ --paths "/*"
