version: 0.2

phases:
  install:
    commands:
      - echo Installing dependencies
  build:
    commands:
      - echo Build started
  post_build:
    commands:
      - echo Build completed

artifacts:
  files:
    - '**/*'
